<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="About.aspx.cs" Inherits="Pages_About" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 style="box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; font-weight: lighter; font-style: normal; color: rgb(0, 0, 0); text-rendering: auto; line-height: 1; font-size: 2.5rem; letter-spacing: -0.05rem; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Trade Registration</h1>
    <p dir="ltr" lang="en" style="box-sizing: border-box; margin: 0px; font-size: 18px; line-height: 26px; color: rgb(51, 51, 51); font-family: &quot;Playfair Display&quot;, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;" xml:lang="en">
        <span style="color: rgb(91, 96, 100); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Did you know that we have been supplying the on-trade for over 50 years! If you have a bar, restaurant, hotel, pub or events company you can now order online through our Drinkfinder website. If you prefer you can give us a call or visit our store if that&#39;s more convenient . Our site is very easy to use and we have one the largest selections of wines, spirits and liqueurs in the country. We work closely with importers, owners and brand ambassadors to bring you the best possible solution 
        for your business. You can rely on quick and efficient delivery, expert advice and excellent customer service.</span></p>
    <div class="row contrast" style="box-sizing: border-box; margin: 0px auto; padding: 0px 45.575px; width: 1519.2px; max-width: 1920px; min-width: 300px; background: rgb(244, 244, 244); color: rgb(51, 51, 51); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <div class="small-12 medium-12 large-12 columns" style="box-sizing: border-box; margin: 0px; padding: 0px 12.85px; width: 1428.05px; float: left; position: relative; font-size: 1rem; line-height: 1.75rem; color: rgb(91, 96, 100); font-weight: lighter;">
            <h2 style="box-sizing: border-box; margin: 60px 0px 0.5rem; padding: 0px; font-family: Roboto, sans-serif; font-weight: lighter; font-style: normal; color: rgb(0, 0, 0); text-rendering: auto; line-height: 1.45; font-size: 1.75rem;">Benefits</h2>
        </div>
    </div>
    <div class="row contrast" style="box-sizing: border-box; margin: 0px auto; padding: 0px 45.575px; width: 1519.2px; max-width: 1920px; min-width: 300px; background: rgb(244, 244, 244); color: rgb(51, 51, 51); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <div class="small-12 medium-12 large-12 columns" style="box-sizing: border-box; margin: 0px; padding: 0px 12.85px; width: 1428.05px; float: left; position: relative; font-size: 1rem; line-height: 1.75rem; color: rgb(91, 96, 100); font-weight: lighter;">
            <ul style="box-sizing: border-box; margin: 0px 0px 1.25rem 1.1rem; padding: 0px; font-size: 0.875rem; line-height: 1.6; list-style-position: outside; font-family: inherit; color: rgb(255, 255, 255);">
                <li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 1rem; line-height: 1.75rem; color: rgb(91, 96, 100); font-weight: lighter;">Competitive pricing.</li>
                <li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 1rem; line-height: 1.75rem; color: rgb(91, 96, 100); font-weight: lighter;">Order easily online or by phone.</li>
                <li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 1rem; line-height: 1.75rem; color: rgb(91, 96, 100); font-weight: lighter;">No minimum order.</li>
                <li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 1rem; line-height: 1.75rem; color: rgb(91, 96, 100); font-weight: lighter;">Free Next Day Delivery on orders over £150.00. UK and weekday delivery only.</li>
                <li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 1rem; line-height: 1.75rem; color: rgb(91, 96, 100); font-weight: lighter;">Expert advice with over 50 years experience in the trade.</li>
                <li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 1rem; line-height: 1.75rem; color: rgb(91, 96, 100); font-weight: lighter;">Thousands of wines, spirits, liqueurs &amp; syrups regularly in stock.</li>
            </ul>
        </div>
    </div>
    <p style="box-sizing: border-box; margin: 0px; font-size: 18px; line-height: 26px; color: rgb(51, 51, 51); font-family: &quot;Playfair Display&quot;, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
</asp:Content>

